export const STAGE_OPTIONS = [
  { value: 'APPEARANCE_OF_ACCUSED_AND_PLEA', label: 'Appearance of Accused & Plea' },
  { value: 'APPEARANCE_OF_PARTIES', label: 'Appearance of Parties' },
  { value: 'APPLICATION_ORDER_39', label: 'Application under Order 39 Rule 1 and 2 (TI)' },
  { value: 'ARGUMENTS', label: 'Arguments' },
  { value: 'AWAIT_MEDIATION_REPORT', label: 'Await Mediation Report' },
  { value: 'AWAIT_ORDERS_FROM_HCK', label: 'Await Orders from HCK' },
  { value: 'BAIL_APPLICATION', label: 'Bail Application' },
  { value: 'CROSS_EXAMINATION_DW', label: 'Cross-examination of DW__' },
  { value: 'CROSS_EXAMINATION_PW', label: 'Cross-examination of PW__' },
  { value: 'DECREE', label: 'Decree' },
  { value: 'DISCHARGE_APPLICATION', label: 'Discharge Application' },
  { value: 'EVIDENCE_OF_PLAINTIFF', label: 'Evidence of Plaintiff' },
  { value: 'EVIDENCE_OF_DEFENDANTS', label: 'Evidence of the Defendants' },
  { value: 'EXAMINATION_IN_CHIEF_DW', label: 'Examination in Chief of DW__' },
  { value: 'EXAMINATION_IN_CHIEF_PW', label: 'Examination in Chief of PW__' },
  { value: 'EXTENSION_OF_INTERIM_ORDER', label: 'Extension of Interim Order Application' },
  { value: 'FIR', label: 'FIR' },
  { value: 'FILING_VAKALATH', label: 'Filing Vakalath' },
  { value: 'FRAMING_OF_CHARGE', label: 'Framing of Charge' },
  { value: 'FURTHER_HEARING', label: 'Further Hearing' },
  { value: 'HEARING_ON_IA', label: 'Hearing on I.A. No. _/202' },
  { value: 'ISSUES', label: 'Issues' },
  { value: 'JUDGEMENT', label: 'Judgement' },
  { value: 'LOK_ADALATH_ADR', label: 'Lok Adalath/ADR' },
  { value: 'MEDIATION', label: 'Mediation' },
  { value: 'NBW', label: 'NBW' },
  { value: 'NOTICE', label: 'Notice' },
  { value: 'OBJECTIONS', label: 'Objections' },
  { value: 'OBJECTIONS_TO_IA', label: 'Objections to I.A. No. _/202' },
  { value: 'ORDERS', label: 'Orders' },
  { value: 'PAPER_PUBLICATION', label: 'Paper Publication' },
  { value: 'PRODUCTION_OF_ADDITIONAL_DOCUMENTS', label: 'Production of Additional Documents' },
  { value: 'PROSECUTION_EVIDENCE', label: 'Prosecution Evidence' },
  { value: 'RE_EXAMINATION', label: 'Re-examination' },
  { value: 'RECALL_AND_REOPEN_APPLICATION', label: 'Recall and Reopen Application' },
  { value: 'REJECTION_OF_PLAINT', label: 'Rejection of the Plaint' },
  { value: 'SETTLEMENT', label: 'Settlement' },
  { value: 'STATEMENT_OF_ACCUSED', label: 'Statement of Accused' },
  { value: 'STEPS', label: 'Steps' },
  { value: 'SUMMONS', label: 'Summons' },
  { value: 'WRITTEN_STATEMENT', label: 'Written Statement' },
] as const;

export const HEARING_STATUS_OPTIONS = [
  { value: 'UPCOMING', label: 'Upcoming' },
  { value: 'PENDING', label: 'Pending Closure' },
  { value: 'CLOSED', label: 'Closed' },
  { value: 'POSTPONED', label: 'Adjourned' },
  { value: 'CANCELLED', label: 'Cancelled' },
] as const;

export const STAGE_LABEL_MAP: Record<string, string> = Object.fromEntries(
  STAGE_OPTIONS.map(({ value, label }) => [value, label])
);
